from typing import TypedDict

class GraphState(TypedDict):
    """
    Represents the state of our graph.

    Attributes:
        init_route_state: The initial route the system should follow (rag, json_analyzer, or anlysis router)
        question: Initial Query given to the system
        file_path: The file path of the document passed in
        json_file_path: 
        doc_anlysis_state: The route the system should follow at the doc analysis junction
        answer: The answer generated by a node
    """

    init_route_state: str  
    question: str  
    file_path: str
    json_file_path: str  
    doc_anlysis_state: str
    answer: str  